version: '3.8'

services:
  e2e-chrome:
    build:
      context: .
    command: "-b chrome"
    volumes:
      - ./artifacts/chrome/videos:/e2e/cypress/videos
      - ./artifacts/chrome/screenshots:/e2e/cypress/screenshots

  e2e-firefox:
    build:
      context: .
    command: "-b firefox -c video=false"
    volumes:
      - ./artifacts/firefox/screenshots:/e2e/cypress/screenshots

  e2e-edge:
    build:
      context: .
    command: "-b edge"
    volumes:
      - ./artifacts/edge/videos:/e2e/cypress/videos
      - ./artifacts/edge/screenshots:/e2e/cypress/screenshots

  e2e-electron:
    build:
      context: .
    volumes:
      - ./artifacts/electron/videos:/e2e/cypress/videos
      - ./artifacts/electron/screenshots:/e2e/cypress/screenshots
